CREATE TABLE analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL,
    job_posting_id BIGINT NOT NULL,
    match_score INTEGER NOT NULL CHECK (match_score BETWEEN 0 AND 100),
    summary TEXT NOT NULL,
    result_json JSONB NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model VARCHAR(128) NOT NULL,
    prompt_version VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analyses_resume
        FOREIGN KEY (resume_id) REFERENCES resumes (id) ON DELETE RESTRICT,
    CONSTRAINT fk_analyses_job_posting
        FOREIGN KEY (job_posting_id) REFERENCES job_postings (id) ON DELETE RESTRICT
);

-- Analyses are immutable historical records. Restricting parent deletion prevents
-- saved results from being silently removed or orphaned.
CREATE INDEX idx_analyses_resume_id ON analyses (resume_id);
CREATE INDEX idx_analyses_job_posting_id ON analyses (job_posting_id);
