CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id BIGINT NOT NULL,
    resume_id BIGINT,
    latest_analysis_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'SAVED',
    applied_at DATE,
    next_action VARCHAR(500),
    next_action_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_job_applications_job_posting UNIQUE (job_posting_id),
    CONSTRAINT chk_job_applications_status
        CHECK (status IN ('SAVED', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN')),
    CONSTRAINT chk_job_applications_notes_length
        CHECK (notes IS NULL OR char_length(notes) <= 10000),
    CONSTRAINT fk_job_applications_job_posting
        FOREIGN KEY (job_posting_id) REFERENCES job_postings (id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_applications_resume
        FOREIGN KEY (resume_id) REFERENCES resumes (id) ON DELETE SET NULL,
    CONSTRAINT fk_job_applications_latest_analysis
        FOREIGN KEY (latest_analysis_id) REFERENCES analyses (id) ON DELETE SET NULL
);

CREATE TABLE application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_application_id BIGINT NOT NULL,
    previous_status VARCHAR(32),
    new_status VARCHAR(32) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_application_history_previous_status
        CHECK (
            previous_status IS NULL
            OR previous_status IN ('SAVED', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN')
        ),
    CONSTRAINT chk_application_history_new_status
        CHECK (new_status IN ('SAVED', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN')),
    CONSTRAINT fk_application_history_application
        FOREIGN KEY (job_application_id) REFERENCES job_applications (id) ON DELETE CASCADE
);

CREATE INDEX idx_job_applications_status_updated
    ON job_applications (status, updated_at DESC);
CREATE INDEX idx_job_applications_resume_id
    ON job_applications (resume_id);
CREATE INDEX idx_job_applications_latest_analysis_id
    ON job_applications (latest_analysis_id);
CREATE INDEX idx_application_history_application_changed
    ON application_status_history (job_application_id, changed_at DESC, id DESC);

-- Tracker records block deletion of their job posting. Optional resume and analysis
-- associations are cleared when those records become unavailable. Deleting a tracker
-- removes only its own status history and never deletes a job, resume, or analysis.
