package com.genesis.applywise.ai;

public enum AnalysisValidationFailure {
    MALFORMED_PROVIDER_RESPONSE,
    EMPTY_PROVIDER_CONTENT,
    TRUNCATED_PROVIDER_RESPONSE,
    JSON_SYNTAX_ERROR,
    MARKDOWN_WRAPPED_JSON,
    RESPONSE_SCHEMA_MISMATCH,
    PROVIDER_REFUSAL,
    INVALID_SCORE,
    MISSING_REQUIRED_COLLECTION,
    BLANK_REQUIRED_COLLECTION_ITEM,
    MISSING_REQUIRED_TEXT,
    MISSING_SKILL_ASSESSMENT,
    BLANK_SKILL_NAME,
    BLANK_SKILL_EXPLANATION,
    UNSUPPORTED_STATUS,
    CONTRADICTORY_STATUS,
    DUPLICATE_SKILL,
    MISSING_REQUIRED_EVIDENCE,
    UNSUPPORTED_EVIDENCE,
    UNSAFE_RECOMMENDATION
}
